// GENERATED by scripts/build-photos.mjs — do not edit by hand.
//
// Every photograph in public/images is reused from Wikimedia Commons under a
// licence permitting commercial use. Several require attribution and, for
// ShareAlike terms, that derivatives carry the same licence — cropping and
// re-encoding makes these derivatives, so the credits below are published at
// /credits and linked from the footer.

export type PhotoCredit = {
  key: string;
  title: string;
  author: string;
  licence: string;
  licenceUrl: string;
  sourceUrl: string;
};

export const photoCredits: PhotoCredit[] = [
  {
    "key": "dirt-bikes/12.jpg",
    "title": "2002ttr250yamahaenduro.jpg",
    "author": "Haridimous at English Wikipedia",
    "licence": "Public domain",
    "licenceUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2002ttr250yamahaenduro.jpg"
  },
  {
    "key": "motorcycles/01.jpg",
    "title": "2014 Yamaha FZ-09.JPG",
    "author": "Dennis Bratland",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2014_Yamaha_FZ-09.JPG"
  },
  {
    "key": "motorcycles/08.jpg",
    "title": "2024 Yamaha MT-09 Y-AMT.jpg",
    "author": "Chanokchon",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2024_Yamaha_MT-09_Y-AMT.jpg"
  },
  {
    "key": "utv/17.jpg",
    "title": "23 Polaris RZR Turbo R Sport.jpg",
    "author": "HJUdall",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:23_Polaris_RZR_Turbo_R_Sport.jpg"
  },
  {
    "key": "utv/16.jpg",
    "title": "24 Polaris RZR Turbo R Sport.jpg",
    "author": "HJUdall",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:24_Polaris_RZR_Turbo_R_Sport.jpg"
  },
  {
    "key": "scooters/18.jpg",
    "title": "A Vespa scooter in Taichung.jpg",
    "author": "chia ying Yang",
    "licence": "CC BY 2.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_Vespa_scooter_in_Taichung.jpg"
  },
  {
    "key": "atvs/15.jpg",
    "title": "All-terrain vehicle HMS Albion.jpg",
    "author": "Antti Leppänen",
    "licence": "CC BY 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:All-terrain_vehicle_HMS_Albion.jpg"
  },
  {
    "key": "dealership/16.jpg",
    "title": "Anther EICMA 2025.jpg",
    "author": "MotorideSA",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Anther_EICMA_2025.jpg"
  },
  {
    "key": "atvs/07.jpg",
    "title": "Arctic Cat 500 4x4 mit POLY CAFS.jpg",
    "author": "Reise Reise",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Arctic_Cat_500_4x4_mit_POLY_CAFS.jpg"
  },
  {
    "key": "atvs/06.jpg",
    "title": "ATV - Quad - SYM Quadlander 200 - Santorini - Greece - 01.jpg",
    "author": "Norbert Nagel",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ATV_-_Quad_-_SYM_Quadlander_200_-_Santorini_-_Greece_-_01.jpg"
  },
  {
    "key": "scooters/12.jpg",
    "title": "Blinkee electric scooter in Budapest (a).jpg",
    "author": "Sir Morosus",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blinkee_electric_scooter_in_Budapest_(a).jpg"
  },
  {
    "key": "scooters/00.jpg",
    "title": "Blinkee electric scooter in Burjassot. 01.jpg",
    "author": "Dorieo",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blinkee_electric_scooter_in_Burjassot._01.jpg"
  },
  {
    "key": "scooters/01.jpg",
    "title": "Blinkee electric scooter in Burjassot. 02.jpg",
    "author": "Dorieo",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blinkee_electric_scooter_in_Burjassot._02.jpg"
  },
  {
    "key": "watercraft/22.jpg",
    "title": "BRP Bombardier Sea-Doo 900 (TL E24D64 G).jpg",
    "author": "This picture belongs to Xavier Caré . Please credit : Xavier Caré / Wikimedia Commons / CC-BY-SA . If you would like special permission to use, license, or purchase the image please contact me to negotiate terms. I'd appreciate if you could let me know about it or mail me ( xavier.care pm.me ) if you want to use this picture out of the Wikimedia project scope.",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:BRP_Bombardier_Sea-Doo_900_(TL_E24D64_G).jpg"
  },
  {
    "key": "watercraft/23.jpg",
    "title": "BRP Bombardier Sea-Doo 900 (TLC14681).jpg",
    "author": "This picture belongs to Xavier Caré . Please credit : Xavier Caré / Wikimedia Commons / CC-BY-SA . If you would like special permission to use, license, or purchase the image please contact me to negotiate terms. I'd appreciate if you could let me know about it or mail me ( xavier.care pm.me ) if you want to use this picture out of the Wikimedia project scope.",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:BRP_Bombardier_Sea-Doo_900_(TLC14681).jpg"
  },
  {
    "key": "generators/14.jpg",
    "title": "Champion 4250 Watt Dual Fuel Open Flame Inverter Generator.jpg",
    "author": "TaurusEmerald",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Champion_4250_Watt_Dual_Fuel_Open_Flame_Inverter_Generator.jpg"
  },
  {
    "key": "golf-carts/00.jpg",
    "title": "Club Car Precedent i3 fleet golf car.jpg",
    "author": "Club Car, LLC",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Club_Car_Precedent_i3_fleet_golf_car.jpg"
  },
  {
    "key": "watercraft/27.jpg",
    "title": "Couple of teenagers riding a personal watercraft splashing on the Mekong in Laos.jpg",
    "author": "Basile Morin",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Couple_of_teenagers_riding_a_personal_watercraft_splashing_on_the_Mekong_in_Laos.jpg"
  },
  {
    "key": "boats/20.jpg",
    "title": "DFC 1296 A small white motorboat with a blue canopy floats on calm water marked TOHATSU THAILAND on its hull and secured by a rope with another boat moored nearby.jpg",
    "author": "PattayaPatrol",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DFC_1296_A_small_white_motorboat_with_a_blue_canopy_floats_on_calm_water_marked_TOHATSU_THAILAND_on_its_hull_and_secured_by_a_rope_with_another_boat_moored_nearby.jpg"
  },
  {
    "key": "boats/00.jpg",
    "title": "DFC 1313 A sleek red and white powerboat number 11 skims across the water at speed with a fishing boat and hazy distant islands on the horizon.jpg",
    "author": "PattayaPatrol",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DFC_1313_A_sleek_red_and_white_powerboat_number_11_skims_across_the_water_at_speed_with_a_fishing_boat_and_hazy_distant_islands_on_the_horizon.jpg"
  },
  {
    "key": "dirt-bikes/02.jpg",
    "title": "Dsc (197294443).jpeg",
    "author": "Sergio Perosino",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dsc_(197294443).jpeg"
  },
  {
    "key": "dealership/13.jpg",
    "title": "FB Mondial Sendero 300 - EICMA 2024.jpg",
    "author": "Saggittarius A",
    "licence": "CC BY 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:FB_Mondial_Sendero_300_-_EICMA_2024.jpg"
  },
  {
    "key": "golf-carts/14.jpg",
    "title": "Golf Carts at Riviera On Vaal 2013.jpg",
    "author": "Ossewa",
    "licence": "CC BY 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Golf_Carts_at_Riviera_On_Vaal_2013.jpg"
  },
  {
    "key": "golf-carts/02.jpg",
    "title": "Golf-cart fairway.jpg",
    "author": "ingagestroliac",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Golf-cart_fairway.jpg"
  },
  {
    "key": "utv/02.jpg",
    "title": "INFRASNOW15 Polaris (1).JPG",
    "author": "Travelarz",
    "licence": "CC BY-SA 3.0 pl",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0/pl/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:INFRASNOW15_Polaris_(1).JPG"
  },
  {
    "key": "watercraft/11.jpg",
    "title": "Jet Ski Australia.jpg",
    "author": "Lowcarb23",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jet_Ski_Australia.jpg"
  },
  {
    "key": "watercraft/14.jpg",
    "title": "Jet skiing in the pristine waters of Kelaa Lagoon.jpg",
    "author": "M.hammadh",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jet_skiing_in_the_pristine_waters_of_Kelaa_Lagoon.jpg"
  },
  {
    "key": "utv/22.jpg",
    "title": "John Deere Gator (1).jpg",
    "author": "Joost J. Bakker from IJmuiden",
    "licence": "CC BY 2.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:John_Deere_Gator_(1).jpg"
  },
  {
    "key": "utv/24.jpg",
    "title": "John Deere Gator 855D (16380637112).jpg",
    "author": "Bob Adams from Amanzimtoti, South Africa",
    "licence": "CC BY-SA 2.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:John_Deere_Gator_855D_(16380637112).jpg"
  },
  {
    "key": "utv/23.jpg",
    "title": "John Deere Gator TX 4x2 (16195639557).jpg",
    "author": "Bob Adams from Amanzimtoti, South Africa",
    "licence": "CC BY-SA 2.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:John_Deere_Gator_TX_4x2_(16195639557).jpg"
  },
  {
    "key": "dirt-bikes/03.jpg",
    "title": "Jump (241881881).jpeg",
    "author": "Ulrich Giraud",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jump_(241881881).jpeg"
  },
  {
    "key": "dirt-bikes/01.jpg",
    "title": "Jump 2 (242030125).jpeg",
    "author": "Ulrich Giraud",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jump_2_(242030125).jpeg"
  },
  {
    "key": "atvs/04.jpg",
    "title": "KTM Quad 990 neutral.jpg",
    "author": "Stefan Krause, Germany",
    "licence": "CC BY 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:KTM_Quad_990_neutral.jpg"
  },
  {
    "key": "boats/13.jpg",
    "title": "LILLE TUT 4933.jpg",
    "author": "Ein Dahmer",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:LILLE_TUT_4933.jpg"
  },
  {
    "key": "generators/15.jpg",
    "title": "Mi-T-M 3000 Watt Inverter Generator.jpg",
    "author": "TaurusEmerald",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mi-T-M_3000_Watt_Inverter_Generator.jpg"
  },
  {
    "key": "dirt-bikes/04.jpg",
    "title": "Might as well - Flickr - pony rojo.jpg",
    "author": "pony rojo from Las Vegas, NV, USA",
    "licence": "CC BY-SA 2.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Might_as_well_-_Flickr_-_pony_rojo.jpg"
  },
  {
    "key": "motorcycles/14.jpg",
    "title": "Moscow, Kaloshin Lane X Arbat, Yamaha MT-09, June 2026 05.jpg",
    "author": "Retired electrician",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Moscow,_Kaloshin_Lane_X_Arbat,_Yamaha_MT-09,_June_2026_05.jpg"
  },
  {
    "key": "motorcycles/09.jpg",
    "title": "Moscow, Yamaha MT-09 Tracer, Aug 2025 02.jpg",
    "author": "Retired electrician",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Moscow,_Yamaha_MT-09_Tracer,_Aug_2025_02.jpg"
  },
  {
    "key": "motorcycles/13.jpg",
    "title": "Moscow, Yamaha MT-09 Tracer, May 2026 01.jpg",
    "author": "Retired electrician",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Moscow,_Yamaha_MT-09_Tracer,_May_2026_01.jpg"
  },
  {
    "key": "motorcycles/12.jpg",
    "title": "Moscow, Yamaha MT-09 Tracer, May 2026 02.jpg",
    "author": "Retired electrician",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Moscow,_Yamaha_MT-09_Tracer,_May_2026_02.jpg"
  },
  {
    "key": "motorcycles/16.jpg",
    "title": "Moscow, Yamaha Tracer MT-09, July 2026 02.jpg",
    "author": "Retired electrician",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Moscow,_Yamaha_Tracer_MT-09,_July_2026_02.jpg"
  },
  {
    "key": "utv/03.jpg",
    "title": "Polaris RZR ATV.JPG",
    "author": "RoyKabanlit",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Polaris_RZR_ATV.JPG"
  },
  {
    "key": "utv/14.jpg",
    "title": "Polaris RZR Pro R.jpg",
    "author": "Rockford Fosgate",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Polaris_RZR_Pro_R.jpg"
  },
  {
    "key": "utv/07.jpg",
    "title": "Polaris RZR XP 1000 EPS - Calico Ghost Town (22699671725).jpg",
    "author": "Tomás Del Coro from Las Vegas, Nevada, USA",
    "licence": "CC BY-SA 2.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Polaris_RZR_XP_1000_EPS_-_Calico_Ghost_Town_(22699671725).jpg"
  },
  {
    "key": "utv/09.jpg",
    "title": "Polaris RZR XP 1000 EPS at Legendy 2018 in Prague.jpg",
    "author": "Jiří Sedláček",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Polaris_RZR_XP_1000_EPS_at_Legendy_2018_in_Prague.jpg"
  },
  {
    "key": "utv/04.jpg",
    "title": "Polaris RZR XP 900.jpg",
    "author": "Tsward318",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Polaris_RZR_XP_900.jpg"
  },
  {
    "key": "utv/01.jpg",
    "title": "Polaris rzr-xp 1000.JPG",
    "author": "Rainmaker47",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Polaris_rzr-xp_1000.JPG"
  },
  {
    "key": "atvs/19.jpg",
    "title": "Polaris Sportsman ATV quad bike.jpg",
    "author": "Andrej Danković",
    "licence": "CC BY 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Polaris_Sportsman_ATV_quad_bike.jpg"
  },
  {
    "key": "generators/00.jpg",
    "title": "Portable electrical generator angle.jpg",
    "author": "Unknown",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Portable_electrical_generator_angle.jpg"
  },
  {
    "key": "generators/16.jpg",
    "title": "Predator 5000 Watt Duel Fuel Super Quiet Inverter Generator.jpg",
    "author": "TaurusEmerald",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Predator_5000_Watt_Duel_Fuel_Super_Quiet_Inverter_Generator.jpg"
  },
  {
    "key": "generators/20.jpg",
    "title": "Pulsar PG4000iSR Inverter Generator.jpg",
    "author": "TaurusEmerald",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pulsar_PG4000iSR_Inverter_Generator.jpg"
  },
  {
    "key": "atvs/05.jpg",
    "title": "Quad Bikes - Flickr - mick - Lumix.jpg",
    "author": "Mick from Northamptonshire, England",
    "licence": "CC BY 2.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Quad_Bikes_-_Flickr_-_mick_-_Lumix.jpg"
  },
  {
    "key": "scooters/19.jpg",
    "title": "Red Vespa scooter in front of Rocca Maggiore, Assisi.jpg",
    "author": "Marco Ober",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Red_Vespa_scooter_in_front_of_Rocca_Maggiore,_Assisi.jpg"
  },
  {
    "key": "watercraft/03.jpg",
    "title": "RIAS 2014 Polizia Jet Ski 02.jpg",
    "author": "Oren Rozen",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:RIAS_2014_Polizia_Jet_Ski_02.jpg"
  },
  {
    "key": "watercraft/04.jpg",
    "title": "RIAS 2014 Polizia Jet Ski 03.jpg",
    "author": "Oren Rozen",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:RIAS_2014_Polizia_Jet_Ski_03.jpg"
  },
  {
    "key": "boats/05.jpg",
    "title": "Saga 20 0479.jpg",
    "author": "Ein Dahmer",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Saga_20_0479.jpg"
  },
  {
    "key": "boats/03.jpg",
    "title": "Saga 24 00162.jpg",
    "author": "Ein Dahmer",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Saga_24_00162.jpg"
  },
  {
    "key": "boats/04.jpg",
    "title": "Saga 24 00163.jpg",
    "author": "Ein Dahmer",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Saga_24_00163.jpg"
  },
  {
    "key": "atvs/24.jpg",
    "title": "Sand Biking.png",
    "author": "Mela2106",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sand_Biking.png"
  },
  {
    "key": "dirt-bikes/17.jpg",
    "title": "Scrambler1200xe.jpg",
    "author": "Scottmcqueen",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Scrambler1200xe.jpg"
  },
  {
    "key": "watercraft/24.jpg",
    "title": "Sea-Doo RXT250 RS, Ribnitz-Damgarten (P1060829).jpg",
    "author": "Matti Blume",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sea-Doo_RXT250_RS,_Ribnitz-Damgarten_(P1060829).jpg"
  },
  {
    "key": "watercraft/19.jpg",
    "title": "Sea-Doo SAR Kokonaisturvallisuus 2015 01.JPG",
    "author": "MKFI",
    "licence": "Public domain",
    "licenceUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sea-Doo_SAR_Kokonaisturvallisuus_2015_01.JPG"
  },
  {
    "key": "dealership/23.jpg",
    "title": "Shriners Auditorium boat show, Wilmington MA.jpg",
    "author": "John Phelan",
    "licence": "CC BY 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Shriners_Auditorium_boat_show,_Wilmington_MA.jpg"
  },
  {
    "key": "scooters/08.jpg",
    "title": "Skuter elektryczny Blinkee City - Sosnowiec, ul. Sobieskiego, Stawiki.jpg",
    "author": "Krzysztof Popławski",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Skuter_elektryczny_Blinkee_City_-_Sosnowiec,_ul._Sobieskiego,_Stawiki.jpg"
  },
  {
    "key": "atvs/11.jpg",
    "title": "Special all-terrain vehicle AM-1 during the \"Armiya 2021\" exhibition (front view).jpg",
    "author": "Kirill Borisenko",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Special_all-terrain_vehicle_AM-1_during_the_%22Armiya_2021%22_exhibition_(front_view).jpg"
  },
  {
    "key": "motorcycles/20.jpg",
    "title": "Suzuki RGV250Γ VJ22A.jpg",
    "author": "PekePON",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Suzuki_RGV250%CE%93_VJ22A.jpg"
  },
  {
    "key": "motorcycles/24.jpg",
    "title": "SUZUKI Γ VJ21A.JPG",
    "author": "Shohei ninomiya",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:SUZUKI_%CE%93_VJ21A.JPG"
  },
  {
    "key": "atvs/09.jpg",
    "title": "TGB Blade 550.jpg",
    "author": "Reise Reise",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:TGB_Blade_550.jpg"
  },
  {
    "key": "dealership/26.jpg",
    "title": "US Navy 090706-N-7427G-001 Electronics Technician 1st Class Dave Israel, a safety inspector assigned to Naval Air Station Joint Reserve Base New Orleans, inspects a loaner motorcycle.jpg",
    "author": "U.S. Navy photo by Mass Communication Specialist 1st Class Shawn D. Graham",
    "licence": "Public domain",
    "licenceUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:US_Navy_090706-N-7427G-001_Electronics_Technician_1st_Class_Dave_Israel,_a_safety_inspector_assigned_to_Naval_Air_Station_Joint_Reserve_Base_New_Orleans,_inspects_a_loaner_motorcycle.jpg"
  },
  {
    "key": "dirt-bikes/00.jpg",
    "title": "USMC-07853.jpg",
    "author": "Unknown",
    "licence": "Public domain",
    "licenceUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:USMC-07853.jpg"
  },
  {
    "key": "golf-carts/09.jpg",
    "title": "Vehicle - Diergaarde Blijdorp - Rotterdam - Golf cart - unknown brand - E.H.B.O. - front left view.jpg",
    "author": "AgainErick",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vehicle_-_Diergaarde_Blijdorp_-_Rotterdam_-_Golf_cart_-_unknown_brand_-_E.H.B.O._-_front_left_view.jpg"
  },
  {
    "key": "golf-carts/11.jpg",
    "title": "Vehicle - Diergaarde Blijdorp - Rotterdam - Golf cart - unknown brand - E.H.B.O. - front view.jpg",
    "author": "AgainErick",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vehicle_-_Diergaarde_Blijdorp_-_Rotterdam_-_Golf_cart_-_unknown_brand_-_E.H.B.O._-_front_view.jpg"
  },
  {
    "key": "golf-carts/10.jpg",
    "title": "Vehicle - Diergaarde Blijdorp - Rotterdam - Golf cart - unknown brand - E.H.B.O. - left side view.jpg",
    "author": "AgainErick",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vehicle_-_Diergaarde_Blijdorp_-_Rotterdam_-_Golf_cart_-_unknown_brand_-_E.H.B.O._-_left_side_view.jpg"
  },
  {
    "key": "generators/13.jpg",
    "title": "Westinghouse iGen4500 Inverter Generator.jpg",
    "author": "TaurusEmerald",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Westinghouse_iGen4500_Inverter_Generator.jpg"
  },
  {
    "key": "motorcycles/04.jpg",
    "title": "Yamaha MT-01 in the Yamaha Communication Plaza.JPG",
    "author": "Rainmaker47",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yamaha_MT-01_in_the_Yamaha_Communication_Plaza.JPG"
  },
  {
    "key": "motorcycles/02.jpg",
    "title": "Yamaha MT-09 2014.jpg",
    "author": "TheMalsa",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yamaha_MT-09_2014.jpg"
  },
  {
    "key": "motorcycles/10.jpg",
    "title": "Yamaha Proto PHEV.jpg",
    "author": "TTTNIS",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yamaha_Proto_PHEV.jpg"
  },
  {
    "key": "atvs/16.jpg",
    "title": "You Look 100% exhibition all-terrain vehicle 20250323 181252.JPG",
    "author": "Svetlov Artem",
    "licence": "CC BY 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:You_Look_100%25_exhibition_all-terrain_vehicle_20250323_181252.JPG"
  }
];
